"""Small, explicit local and SSH executors used by v2 preflight and runner."""

from __future__ import annotations

import shlex
import socket
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from .model import Machine


class ExecutionError(RuntimeError):
    """A destination command could not be executed or failed."""


@dataclass(frozen=True)
class CommandResult:
    argv: tuple[str, ...]
    returncode: int
    stdout: str
    stderr: str


class Executor:
    def run(self, argv: Sequence[str], *, timeout: float = 30.0) -> CommandResult:
        raise NotImplementedError


class LocalExecutor(Executor):
    def run(self, argv: Sequence[str], *, timeout: float = 30.0) -> CommandResult:
        try:
            completed = subprocess.run(list(argv), capture_output=True, text=True, timeout=timeout)
        except subprocess.TimeoutExpired as exc:
            stdout = exc.stdout or ""
            stderr = (exc.stderr or "") + f"\ncommand timed out after {timeout:.0f}s"
            return CommandResult(tuple(argv), 124, stdout if isinstance(stdout, str) else stdout.decode(errors="replace"), stderr)
        return CommandResult(tuple(argv), completed.returncode, completed.stdout, completed.stderr)


class SshExecutor(Executor):
    def __init__(self, machine: Machine):
        self.machine = machine

    def run(self, argv: Sequence[str], *, timeout: float = 30.0) -> CommandResult:
        ssh = self.machine.ssh
        command = ["ssh", "-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=yes", "-i", ssh.private_key_file, "-p", str(ssh.port)]
        if ssh.known_hosts_file:
            command.extend(["-o", f"UserKnownHostsFile={ssh.known_hosts_file}"])
        command.append(f"{ssh.user}@{self.machine.management_address}")
        command.append(shlex.join(argv))
        completed = subprocess.run(command, capture_output=True, text=True, timeout=timeout)
        return CommandResult(tuple(command), completed.returncode, completed.stdout, completed.stderr)

    def transfer(self, source: Path, destination: str, *, excludes: tuple[str, ...] = (), timeout: float = 300.0) -> CommandResult:
        ssh = self.machine.ssh
        command = ["rsync", "-az", "-e", shlex.join(["ssh", "-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=yes", "-i", ssh.private_key_file, "-p", str(ssh.port)])]
        if ssh.known_hosts_file:
            command[-1] += " " + shlex.join(["-o", f"UserKnownHostsFile={ssh.known_hosts_file}"])
        for pattern in excludes:
            command.extend(("--exclude", pattern))
        source_spec = f"{source}/" if source.is_dir() else str(source)
        destination_spec = f"{ssh.user}@{self.machine.management_address}:{destination}/"
        command.extend([source_spec, destination_spec])
        completed = subprocess.run(command, capture_output=True, text=True, timeout=timeout)
        return CommandResult(tuple(command), completed.returncode, completed.stdout, completed.stderr)


def _local_addresses() -> set[str]:
    values = {"127.0.0.1", "::1"}
    for hostname in (socket.gethostname(), socket.getfqdn()):
        try:
            values.update(item[4][0] for item in socket.getaddrinfo(hostname, None))
        except socket.gaierror:
            continue
    return values


def resolve_executor(machine: Machine) -> Executor:
    if machine.execution == "local":
        return LocalExecutor()
    if machine.execution == "ssh":
        return SshExecutor(machine)
    try:
        management = {item[4][0] for item in socket.getaddrinfo(machine.management_address, None)}
    except socket.gaierror as exc:
        raise ExecutionError(f"cannot resolve auto machine {machine.id}: {machine.management_address}") from exc
    local = _local_addresses()
    matching = management.intersection(local)
    if matching:
        if len(management) != len(matching):
            raise ExecutionError(f"auto machine {machine.id} resolves to both local and remote addresses")
        return LocalExecutor()
    return SshExecutor(machine)


def run_preflight(machine: Machine) -> list[dict[str, str | bool]]:
    """Run only read-only checks. It never creates paths, networks or containers."""
    executor = resolve_executor(machine)
    commands = {
        "docker": ("docker", "info", "--format", "{{.ID}}"),
        "compose": ("docker", "compose", "version", "--short"),
        "architecture": ("uname", "-m"),
    }
    # Local runs are staged below .generated by the runner, so production
    # destination paths such as /srv/dark must not gate a local Docker test.
    if machine.execution != "local":
        commands.update({
            # data_root is intentionally created by apply; measure the
            # existing parent during this read-only preflight instead.
            "disk_space": ("sh", "-lc", f"test $(df -Pk {shlex.quote(str(Path(machine.data_root).parent))} | awk 'NR==2 {{print $4}}') -gt 1048576"),
            "workspace_parent": ("test", "-d", str(Path(machine.workspace_root).parent)),
            "workspace_parent_writable": ("test", "-w", str(Path(machine.workspace_root).parent)),
            "data_parent": ("test", "-d", str(Path(machine.data_root).parent)),
            "data_parent_writable": ("test", "-w", str(Path(machine.data_root).parent)),
            "secrets_parent": ("test", "-d", str(Path(machine.secrets_root).parent)),
            "secrets_parent_writable": ("test", "-w", str(Path(machine.secrets_root).parent)),
        })
        commands.update({f"address:{network}": ("sh", "-lc", f"ip -4 addr show | grep -q 'inet {address}/'") for network, address in machine.addresses.items()})
    results: list[dict[str, str | bool]] = []
    for name, argv in commands.items():
        result = executor.run(argv)
        results.append({
            "check": name,
            "ok": result.returncode == 0,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
        })
    return results
