"""Small, explicit local and SSH executors used by v2 preflight and runner."""

from __future__ import annotations

import shlex
import socket
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from .model import Machine
from .network import p2p_endpoint, p2p_edges


class ExecutionError(RuntimeError):
    """A destination command could not be executed or failed."""


@dataclass(frozen=True)
class CommandResult:
    argv: tuple[str, ...]
    returncode: int
    stdout: str
    stderr: str


class Executor:
    def run(self, argv: Sequence[str], *, timeout: float = 30.0) -> CommandResult:
        raise NotImplementedError


class LocalExecutor(Executor):
    def run(self, argv: Sequence[str], *, timeout: float = 30.0) -> CommandResult:
        try:
            completed = subprocess.run(list(argv), capture_output=True, text=True, timeout=timeout)
        except subprocess.TimeoutExpired as exc:
            stdout = exc.stdout or ""
            stderr = (exc.stderr or "") + f"\ncommand timed out after {timeout:.0f}s"
            return CommandResult(tuple(argv), 124, stdout if isinstance(stdout, str) else stdout.decode(errors="replace"), stderr)
        return CommandResult(tuple(argv), completed.returncode, completed.stdout, completed.stderr)


class SshExecutor(Executor):
    def __init__(self, machine: Machine):
        self.machine = machine

    def run(self, argv: Sequence[str], *, timeout: float = 30.0) -> CommandResult:
        ssh = self.machine.ssh
        command = ["ssh", "-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=yes", "-i", ssh.private_key_file, "-p", str(ssh.port)]
        if ssh.known_hosts_file:
            command.extend(["-o", f"UserKnownHostsFile={ssh.known_hosts_file}"])
        command.append(f"{ssh.user}@{self.machine.management_address}")
        command.append(shlex.join(argv))
        completed = subprocess.run(command, capture_output=True, text=True, timeout=timeout)
        return CommandResult(tuple(command), completed.returncode, completed.stdout, completed.stderr)

    def transfer(self, source: Path, destination: str, *, excludes: tuple[str, ...] = (), timeout: float = 300.0) -> CommandResult:
        ssh = self.machine.ssh
        command = ["rsync", "-az", "-e", shlex.join(["ssh", "-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=yes", "-i", ssh.private_key_file, "-p", str(ssh.port)])]
        if ssh.known_hosts_file:
            command[-1] += " " + shlex.join(["-o", f"UserKnownHostsFile={ssh.known_hosts_file}"])
        for pattern in excludes:
            command.extend(("--exclude", pattern))
        source_spec = f"{source}/" if source.is_dir() else str(source)
        destination_spec = f"{ssh.user}@{self.machine.management_address}:{destination}/"
        command.extend([source_spec, destination_spec])
        completed = subprocess.run(command, capture_output=True, text=True, timeout=timeout)
        return CommandResult(tuple(command), completed.returncode, completed.stdout, completed.stderr)


def _local_addresses() -> set[str]:
    values = {"127.0.0.1", "::1"}
    for hostname in (socket.gethostname(), socket.getfqdn()):
        try:
            values.update(item[4][0] for item in socket.getaddrinfo(hostname, None))
        except socket.gaierror:
            continue
    return values


def resolve_executor(machine: Machine) -> Executor:
    if machine.execution in {"local", "docker-lab"}:
        return LocalExecutor()
    if machine.execution == "ssh":
        return SshExecutor(machine)
    try:
        management = {item[4][0] for item in socket.getaddrinfo(machine.management_address, None)}
    except socket.gaierror as exc:
        raise ExecutionError(f"cannot resolve auto machine {machine.id}: {machine.management_address}") from exc
    local = _local_addresses()
    matching = management.intersection(local)
    if matching:
        if len(management) != len(matching):
            raise ExecutionError(f"auto machine {machine.id} resolves to both local and remote addresses")
        return LocalExecutor()
    return SshExecutor(machine)


def run_preflight(machine: Machine) -> list[dict[str, str | bool]]:
    """Run only read-only checks. It never creates paths, networks or containers."""
    executor = resolve_executor(machine)
    commands = {
        "docker": ("docker", "info", "--format", "{{.ID}}"),
        "compose": ("docker", "compose", "version", "--short"),
        "architecture": ("uname", "-m"),
    }
    # Local runs are staged below .generated by the runner, so production
    # destination paths such as /srv/dark must not gate a local Docker test.
    if machine.execution not in {"local", "docker-lab"}:
        commands.update({
            # data_root is intentionally created by apply; measure the
            # existing parent during this read-only preflight instead.
            "disk_space": ("sh", "-lc", f"test $(df -Pk {shlex.quote(str(Path(machine.data_root).parent))} | awk 'NR==2 {{print $4}}') -gt 1048576"),
            "workspace_parent": ("test", "-d", str(Path(machine.workspace_root).parent)),
            "workspace_parent_writable": ("test", "-w", str(Path(machine.workspace_root).parent)),
            "data_parent": ("test", "-d", str(Path(machine.data_root).parent)),
            "data_parent_writable": ("test", "-w", str(Path(machine.data_root).parent)),
            "secrets_parent": ("test", "-d", str(Path(machine.secrets_root).parent)),
            "secrets_parent_writable": ("test", "-w", str(Path(machine.secrets_root).parent)),
        })
        commands.update({f"address:{network}": ("sh", "-lc", f"ip -4 addr show | grep -q 'inet {address}/'") for network, address in machine.addresses.items()})
    results: list[dict[str, str | bool]] = []
    for name, argv in commands.items():
        result = executor.run(argv)
        results.append({
            "check": name,
            "ok": result.returncode == 0,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
        })
    return results


def run_network_preflight(plan) -> list[dict[str, str | bool]]:
    """Check that each remote consumer has an IP route to its declared endpoint."""
    results: list[dict[str, str | bool]] = []
    seen: set[tuple[str, str, int, str]] = set()
    by_id = {service.id: service for service in plan.services}
    for consumer in plan.services:
        for connection in consumer.connections.values():
            provider = by_id[connection["service"]]
            # Contract deployment is a one-shot producer.  Its generated
            # runtime is distributed explicitly by the runner, not through a
            # TCP endpoint, so it has no entry in ``plan.endpoints``.
            if provider.type == "contracts-deploy":
                continue
            if provider.machine_id == consumer.machine_id:
                continue
            endpoint = next(item for item in plan.endpoints if item.service == provider.id and item.transport in {"private", "docker"} and item.network == connection.get("network"))
            key = (consumer.machine_id, endpoint.host, endpoint.port, provider.id)
            if key in seen:
                continue
            seen.add(key)
            machine = plan.machine(consumer.machine_id)
            if machine.execution in {"local", "docker-lab"}:
                results.append({"check": f"route:{consumer.id}->{provider.id}", "ok": True, "stdout": "local execution; route verified by service readiness", "stderr": ""})
                continue
            result = resolve_executor(machine).run(("sh", "-lc", f"ip route get {shlex.quote(endpoint.host)} >/dev/null"), timeout=15)
            results.append({
                "check": f"route:{consumer.id}->{provider.id}:{endpoint.host}:{endpoint.port}",
                "ok": result.returncode == 0,
                "stdout": result.stdout.strip(),
                "stderr": result.stderr.strip(),
            })
    for policy, types, default_port in (
        ("besu", {"besu-rpc", "besu-validator", "besu-observer"}, 30303),
        ("ipfs", {"ipfs-kubo"}, int(plan.raw["infrastructure"]["ipfs"]["swarm_port"])),
        ("cluster", {"ipfs-cluster"}, int(plan.raw["infrastructure"]["cluster"]["p2p_port"])),
    ):
        peers = [service for service in plan.services if service.type in types]
        family = {"besu": "blockchain", "ipfs": "ipfs", "cluster": "cluster"}[policy]
        explicit = plan.raw.get("peerings", {}).get(family, [])
        if explicit:
            for edge in explicit:
                consumer, provider = by_id[edge["from"]], by_id[edge["to"]]
                key = (consumer.machine_id, edge["address"], int(edge["port"]), f"{policy}-p2p")
                if key in seen:
                    continue
                seen.add(key)
                machine = plan.machine(consumer.machine_id)
                if machine.execution in {"local", "docker-lab"}:
                    results.append({"check": f"p2p-route:{consumer.id}->{provider.id}", "ok": True, "stdout": "local execution; route verified by P2P readiness", "stderr": ""})
                    continue
                result = resolve_executor(machine).run(("sh", "-lc", f"ip route get {shlex.quote(edge['address'])} >/dev/null"), timeout=15)
                results.append({"check": f"p2p-route:{consumer.id}->{provider.id}:{edge['address']}:{edge['port']}", "ok": result.returncode == 0, "stdout": result.stdout.strip(), "stderr": result.stderr.strip()})
            continue
        network = plan.raw["infrastructure"][policy]["network"]
        for consumer in peers:
            for provider in peers:
                if consumer.machine_id == provider.machine_id:
                    continue
                host, port = p2p_endpoint(plan.machine(provider.machine_id), provider, network, default_port)
                key = (consumer.machine_id, host, port, f"{policy}-p2p")
                if key in seen:
                    continue
                seen.add(key)
                machine = plan.machine(consumer.machine_id)
                if machine.execution in {"local", "docker-lab"}:
                    results.append({"check": f"p2p-route:{consumer.id}->{provider.id}", "ok": True, "stdout": "local execution; route verified by P2P readiness", "stderr": ""})
                    continue
                result = resolve_executor(machine).run(("sh", "-lc", f"ip route get {shlex.quote(host)} >/dev/null"), timeout=15)
                results.append({
                    "check": f"p2p-route:{consumer.id}->{provider.id}:{host}:{port}",
                    "ok": result.returncode == 0,
                    "stdout": result.stdout.strip(),
                    "stderr": result.stderr.strip(),
                })
    return results
