# Local parameters for the current AWS account. Do not commit this file.
Parameters:
  DeploymentName: dark2-prod-aws
  ResourceNamePrefix: dark-prod-
  Environment: production
  VpcCidr: 10.20.0.0/16
  AlbSubnetCidr: 10.20.0.0/24
  WorkloadSubnetCidr: 10.20.10.0/24
  ImageId: /aws/service/canonical/ubuntu/server/26.04/stable/current/arm64/hvm/ebs-gp3/ami-id
  KeyName: lareferencia-dark
  DeployUser: ubuntu
  AppsInstanceType: c7g.2xlarge
  ResolverInstanceType: c7g.large
  BlockchainInstanceType: c7g.xlarge
  StorageInstanceType: c7g.large
  AppsDataVolumeGiB: '120'
  ResolverDataVolumeGiB: '60'
  BlockchainDataVolumeGiB: '120'
  StorageDataVolumeGiB: '250'
  AppsHostname: minter-01.dark-pid.net
  ResolverHostname: resolver-01.dark-pid.net
  AcmCertificateArn: arn:aws:acm:us-east-1:524284048780:certificate/8e88e4cc-8765-48ec-8af7-5fb705dc7401
  HostedZoneId: Z05395502DJG3KJD1RXP2
  EnableDeletionProtection: 'true'
  RetainDataVolumes: 'false'
Tags:
  dARKManagedBy: rain
  dARKProfile: dark2-prod-aws
